source $HOME/.config/nvim/config/init.vimrc
source $HOME/.config/nvim/config/features.vimrc
source $HOME/.config/nvim/config/appearance.vimrc
source $HOME/.config/nvim/config/general.vimrc
source $HOME/.config/nvim/config/indentation.vimrc
source $HOME/.config/nvim/config/mappings.vimrc
source $HOME/.config/nvim/config/other.vimrc
source $HOME/.config/nvim/config/plugins.vimrc
source $HOME/.config/nvim/config/usability.vimrc
